export const LinkList = [
    {
        id:1,
        name:'About',
        path:'/aboutUs/aboutUs',
    },
    {
        id:2,
        name:'Affiliates',
        path:'/affiliated/affiliated',
    },
    {
        id:3,
        name:'Resources',
        path:'/resources/resources',
    },
    {
        id:4,
        name:'Contact',
        path:'/contact/contact',
    }
];
